FROM rust:1.75-slim as builder
WORKDIR /app
COPY . .
# Compilación optimizada para el demo
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/power-auditor .
CMD ["./power-auditor"]
