version: '3.8'

services:
  # --- CAPA DE INGESTIÓN (EL FILTRO) ---
  cold-gateway:
    container_name: cold-gateway-go
    build: 
      context: ./services/ingestion-go
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=core_cold_twin_secret_2026
    networks:
      - retail-hurricane-net
    restart: always

  # --- CAPA DE INTELIGENCIA (EL CEREBRO) ---
  twin-brain:
    container_name: twin-brain-python
    build: 
      context: ./services/inference-py
    volumes:
      - ./models:/app/models # Para cargar tus Redes Siamesas
    depends_on:
      - redis-cache
    networks:
      - retail-hurricane-net
    restart: always

  # --- CAPA DE INTEGRIDAD (EL AUDITOR) ---
  power-audit:
    container_name: power-audit-rust
    build: 
      context: ./services/audit-rust
    depends_on:
      - db-core
    networks:
      - retail-hurricane-net
    restart: always

  # --- INFRAESTRUCTURA DE DATOS (EL CORAZÓN) ---
  db-core:
    image: postgres:16-alpine
    container_name: core-db-sql
    environment:
      POSTGRES_DB: retail_audit
      POSTGRES_USER: edmundo_admin
      POSTGRES_PASSWORD: power_password_2026
    ports:
      - "5432:5432"
    networks:
      - retail-hurricane-net

  redis-cache:
    image: redis:7-alpine
    container_name: core-cache-speed
    networks:
      - retail-hurricane-net

# RED INTERNA SEGURA (ZERO-TRUST CONCEPT)
networks:
  retail-hurricane-net:
    driver: bridge
